# Generated by Django 5.2.1 on 2025-05-13 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskstatus",
            name="code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddConstraint(
            model_name="taskstatus",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="unique_task_status_code_for_tenant"
            ),
        ),
    ]
