# Generated by Django 5.2.1 on 2025-05-19 22:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("tasks", "0002_taskstatus_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="status",
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Name of board.", max_length=255)),
                ("code", models.CharField(blank=True, default="", max_length=50)),
                ("order", models.PositiveIntegerField(help_text="Order of board.")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Determines whether board is default (todo, done, in review, etc).",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created board.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_boards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant that owns this board.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the last change.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_boards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="board",
            field=models.ForeignKey(
                blank=True,
                help_text="Board of task.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.board",
            ),
        ),
        migrations.DeleteModel(
            name="TaskStatus",
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.UniqueConstraint(
                fields=("tenant", "order"), name="unique_border_order_for_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="unique_border_code_code_for_tenant"
            ),
        ),
    ]
