# Generated by Django 5.2.2 on 2025-06-09 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0002_project_owner_project_responsible_project_supervisor_and_more",
        ),
        ("tasks", "0003_remove_task_status_board_task_board_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="board",
            name="unique_border_order_for_tenant",
        ),
        migrations.RemoveConstraint(
            model_name="board",
            name="unique_border_code_code_for_tenant",
        ),
        migrations.RemoveField(
            model_name="board",
            name="code",
        ),
        migrations.RemoveField(
            model_name="board",
            name="is_default",
        ),
        migrations.RemoveField(
            model_name="board",
            name="tenant",
        ),
        migrations.AddField(
            model_name="board",
            name="project",
            field=models.ForeignKey(
                default="6445f744-c61d-4502-8308-ee4d1ac15da0",
                help_text="Project that owns this board.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boards",
                to="projects.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="board",
            name="type",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("in_review", "In Review"),
                    ("done", "Done"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.UniqueConstraint(
                fields=("project", "order"), name="unique_border_order_for_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("type__in", ["todo", "in_progress", "in_review", "done"])
                ),
                fields=("project", "type"),
                name="unique_border_type_for_project",
            ),
        ),
    ]
