# Generated by Django 5.2.2 on 2025-06-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_remove_board_unique_border_order_for_tenant_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="board",
            name="unique_border_type_for_project",
        ),
        migrations.RemoveField(
            model_name="board",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="board",
            name="type",
        ),
        migrations.RemoveField(
            model_name="board",
            name="updated_by",
        ),
    ]
