# Generated by Django 5.2.2 on 2025-06-09 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='owner',
            field=models.ForeignKey(default='03faccc3-8cb5-44aa-b9e6-cf88d9faa0a3', help_text='Owner of tenant', on_delete=django.db.models.deletion.PROTECT, related_name='owned_tenants', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'User')], default='user', help_text='Role of user in tenant.', max_length=20),
        ),
    ]
