# Generated by Django 5.2.2 on 2025-06-11 14:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_tenant_owner_alter_tenantmembership_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_tenant_name_for_owner"
            ),
        ),
    ]
