# Generated by Django 5.2.2 on 2025-06-11 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tenant_unique_tenant_name_for_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="sub_domain",
            field=models.CharField(
                help_text="Subdomain of tenant.",
                max_length=63,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Subdomain must contain only lowercase letters, numbers and hyphens, and cannot start or end with a hyphen.",
                        regex="^[a-z0-9]+(-[a-z0-9]+)*$",
                    )
                ],
            ),
        ),
    ]
