# Generated by Django 5.2.2 on 2025-06-09 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='Responsible of project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor of project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('guest', 'Guest'), ('reader', 'Reader')], default='user', help_text='Role of user in project.', max_length=20),
        ),
    ]
