# Generated by Django 5.2.2 on 2025-06-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0002_project_owner_project_responsible_project_supervisor_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="responsible",
        ),
    ]
