# Generated by Django 5.2.1 on 2025-05-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentattachment",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AlterModelOptions(
            name="taskattachment",
            options={"ordering": ["-uploaded_at"]},
        ),
    ]
