# Generated by Django 5.2.2 on 2025-06-09 17:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0002_alter_commentattachment_options_and_more"),
        ("comments", "0001_initial"),
        ("tasks", "0004_remove_board_unique_border_order_for_tenant_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskattachment",
            name="task",
        ),
        migrations.RemoveField(
            model_name="taskattachment",
            name="uploaded_by",
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="attachments/")),
                (
                    "uploaded_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="comments.comment",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tasks.task",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded this attachment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.DeleteModel(
            name="CommentAttachment",
        ),
        migrations.DeleteModel(
            name="TaskAttachment",
        ),
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("task__isnull", False), ("comment__isnull", True)),
                    models.Q(("task__isnull", True), ("comment__isnull", False)),
                    _connector="OR",
                ),
                name="attachment_task_xor_comment",
            ),
        ),
    ]
